version: '3.2'
services:
  sborka:
    build: work7/sborka/
    container_name: sborka1
    volumes:
      - app-data28:/tmp/webapp/

  prod:
    build: work7/prod/
    container_name: prod1
    ports:
      - "8080:8080"
    volumes:
      - app-data28:/usr/local/tomcat/webapps/

volumes:
  app-data28: {}




