version: '3.2'
services:
  sborka:
    build: work7/sborka/
    container_name: sborka1
    volumes:
      - app-data18:/tmp/webapp/

  prod:
    build: work7/prod/
    container_name: prod1
    ports:
      - "8080:8080"
    volumes:
      - app-data19:/usr/share/apache-tomcat-9.0.68/webapps/



volumes:
  app-data18: {}
  app-data19: {}



