version: '3.7'

services:
  sborka:
    build: work7/sborka/
    container_name: sborka7
    volumes:
      - ./tmp/work7_1:/tmp/test/boxfuse-sample-java-war-hello/target
  
  prod:
    build: work7/prod/
    container_name: prod
    volumes: - ./tmp/work7_1:/tmp/test/boxfuse-sample-java-war-hello/target
      

volumes:
  sborka:




