version: '3.2'
services:
  builder:
    build: ./sborka
    volumes:
     - war:/java_mysql/target


  web:
    build: ./prod
    volumes:
     - war:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: java_mysql
      MYSQL_PASSWORD: java_mysql_pass
      MYSQL_DATABASE: java_mysql_db
      MYSQL_ROOT_PASSWORD: java_mysql_pass
    volumes:
      - mysql_data:/var/lib/mysql
    

volumes:
  war:
  mysql_data:
