---
- name: build  java app
  hosts: build
  become: yes

  tasks:
  - name: ensure update linux packages is present
    apt:
      name: update_cache=yes force_apt_get=yes cache_valid_time=3600
      state: present
  
  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: ensure maven packages is present
    apt:
      name: maven
      state: present

  - name: ensure maven service is started
    service:
      name: maven
      state: started

  - name: ensure git packages is present
    apt:
      name: git
      state: present

