---
- name: build  java app
  hosts: build
  become: yes

  tasks:
  - name: update linux packages
    apt:
      update_cache: yes
      cache_valid_time: 86400
      
  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: ensure maven packages is present
    apt:
      name: maven
      state: present

  - name: ensure git packages is present
    apt:
      name: git
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/danila/lesson8
      clone: yes
      update: yes

  - name: Compile and package
    shell: mvn package -f /home/danila/lesson8

  - name: fetch war file
    ansible.builtin.fetch:
      src: /home/danila/lesson8/target/hello-1.0.war
      dest: /home/danila/lesson8/devopschool/lesson8



    


  # - name: transfer data from build to prod
  #   copy:
  #     src=/home/danila/lesson8/target
  #     dest=/home/danila/
  #   delegate_to: prod


# - hosts: prod
#   tasks:    
#    - name: Copy Remote-To-Remote (from build to prod)
#      synchronize: src=/home/danila/lesson8/target dest=/home/danila
#      delegate_to: build
#      become: yes



# - name: run java app
#   hosts: prod
#   become: yes

#   tasks:
#   - name: update linux packages
#     apt:
#       update_cache: yes
#       cache_valid_time: 86400
      
#   - name: ensure default-jdk packages is present
#     apt:
#       name: default-jdk
#       state: present

