---
- name: build  java app
  hosts: build
  become: yes

  tasks:
  - name: ensure update linux packages is present
    apt:
      update_cache: yes
      cache_valid_time: 86400
      
  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: ensure maven packages is present
    apt:
      name: maven
      state: present

  - name: ensure maven service is started
    service:
      name: maven
      state: started

  - name: ensure git packages is present
    apt:
      name: git
      state: present

