---
- name: build  java app
  hosts: build
  become: yes

  tasks:
  - name: update linux packages
    apt:
      update_cache: yes
      cache_valid_time: 86400
      
  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: ensure maven packages is present
    apt:
      name: maven
      state: present

  - name: ensure git packages is present
    apt:
      name: git
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/danila/lesson8_1
      clone: yes
      update: yes

  - name: Compile and package
    command: './mvnw clean install'
    args:
      chdir: "/home/danila/lesson8_1"

