---
- name: build  java app
  hosts: build
  become: yes

  tasks:
  - name: update linux packages
    apt:
      update_cache: yes
      cache_valid_time: 86400
      
  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: ensure maven packages is present
    apt:
      name: maven
      state: present

  - name: ensure git packages is present
    apt:
      name: git
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/danila/lesson8
      clone: yes
      update: yes

  - name: Compile and package
    shell: mvn package -f /home/danila/lesson8

  - name: fetch war file to Control node
    fetch:
      src: /home/danila/lesson8/target/hello-1.0.war
      dest: /home/danila/lesson8/devopschool/lesson8/hello.war
      flat: true


- name: run java app
  hosts: prod
  become: yes

  tasks: 
  - name: update linux packages
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: ensure default-jdk packages is present
    apt:
      name: default-jdk
      state: present

  - name: Create a Tomcat Directory
    file:
      path: /opt/tomcat9
      state: directory

  - name: download and unarchive tomcat
    unarchive: 
      src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
      dest: /opt/tomcat9
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Creating service for Apache tomcat.
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch
      mode: u+rwx,g-rwx,o-x

  - name: copy war file to prod
    copy:
      src: /home/danila/lesson8/devopschool/lesson8/hello.war
      dest: /opt/tomcat9/webapps
      


