---
- name: intall packages
  apt: name={{ item }} state=present
  with_items:
    - maven
    - git

   - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/danila/lesson9/hello
      clone: yes
      update: yes

- name: Compile and package
    shell: mvn package -f /home/danila/lesson9/hello/

- name: fetch war file to Control node
    fetch:
      src: /home/danila/lesson9/hello/target/hello-1.0.war
      dest: /home/danila/lesson9/hello.war
      flat: true